spring:
  application:
    name: settings-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/finanscepte_settings}

server:
  port: 8091

finanscepte:
  user-service-url: ${USER_SERVICE_URL:http://localhost:8081}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.finanscepte: DEBUG
